### PR TITLE
Added PickerView with expansion cell

### PR DESCRIPTION
**Pull request by Niko-r**

### CODE REVIEW

**Comment by davdroman** [comment]
I see what you're trying to do here. It's a pretty good idea, but I think we can take it further.

What if we added this functionality to `BOChoiceTableViewCell` as an optional way to choose an option? I can think of a `mode` property defining whether the cell works via taps or the picker view itself.

What do you think?

**Comment by mythodeia** [comment]
@DavdRoman excellent idea! this way the user would be able to choose a preferred way

**Comment by davdroman** [comment]
Good to hear your thoughts, @mythodeia :smile:

**Comment by Niko-r** [comment]
@DavdRoman at the beginning I was shared between including it into `BOChoiceTableViewCell`, or make it "independent" in case it would be pushed further in customization/functionnalities. 
A `mode` option is a good idea, and I'm fine with it if you want to go this way ;-)

**Comment by davdroman** [comment]
Exactly my thoughts too, although I think the case is simple enough to mix it into a simple cell.

**Pull request closed without merging**
